# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/curusarn/git/ctu-fit-mi-gen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/curusarn/git/ctu-fit-mi-gen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/curusarn/git/ctu-fit-mi-gen/CMakeFiles /home/curusarn/git/ctu-fit-mi-gen/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/curusarn/git/ctu-fit-mi-gen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mila+

# Build rule for target.
mila+: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mila+
.PHONY : mila+

# fast build rule for target.
mila+/fast:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/build
.PHONY : mila+/fast

src/compiler.o: src/compiler.cpp.o

.PHONY : src/compiler.o

# target to build an object file
src/compiler.cpp.o:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/compiler.cpp.o
.PHONY : src/compiler.cpp.o

src/compiler.i: src/compiler.cpp.i

.PHONY : src/compiler.i

# target to preprocess a source file
src/compiler.cpp.i:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/compiler.cpp.i
.PHONY : src/compiler.cpp.i

src/compiler.s: src/compiler.cpp.s

.PHONY : src/compiler.s

# target to generate assembly for a file
src/compiler.cpp.s:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/compiler.cpp.s
.PHONY : src/compiler.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mila/ast.o: src/mila/ast.cpp.o

.PHONY : src/mila/ast.o

# target to build an object file
src/mila/ast.cpp.o:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/mila/ast.cpp.o
.PHONY : src/mila/ast.cpp.o

src/mila/ast.i: src/mila/ast.cpp.i

.PHONY : src/mila/ast.i

# target to preprocess a source file
src/mila/ast.cpp.i:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/mila/ast.cpp.i
.PHONY : src/mila/ast.cpp.i

src/mila/ast.s: src/mila/ast.cpp.s

.PHONY : src/mila/ast.s

# target to generate assembly for a file
src/mila/ast.cpp.s:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/mila/ast.cpp.s
.PHONY : src/mila/ast.cpp.s

src/mila/parser.o: src/mila/parser.cpp.o

.PHONY : src/mila/parser.o

# target to build an object file
src/mila/parser.cpp.o:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/mila/parser.cpp.o
.PHONY : src/mila/parser.cpp.o

src/mila/parser.i: src/mila/parser.cpp.i

.PHONY : src/mila/parser.i

# target to preprocess a source file
src/mila/parser.cpp.i:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/mila/parser.cpp.i
.PHONY : src/mila/parser.cpp.i

src/mila/parser.s: src/mila/parser.cpp.s

.PHONY : src/mila/parser.s

# target to generate assembly for a file
src/mila/parser.cpp.s:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/mila/parser.cpp.s
.PHONY : src/mila/parser.cpp.s

src/mila/scanner.o: src/mila/scanner.cpp.o

.PHONY : src/mila/scanner.o

# target to build an object file
src/mila/scanner.cpp.o:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/mila/scanner.cpp.o
.PHONY : src/mila/scanner.cpp.o

src/mila/scanner.i: src/mila/scanner.cpp.i

.PHONY : src/mila/scanner.i

# target to preprocess a source file
src/mila/scanner.cpp.i:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/mila/scanner.cpp.i
.PHONY : src/mila/scanner.cpp.i

src/mila/scanner.s: src/mila/scanner.cpp.s

.PHONY : src/mila/scanner.s

# target to generate assembly for a file
src/mila/scanner.cpp.s:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/mila/scanner.cpp.s
.PHONY : src/mila/scanner.cpp.s

src/runtime.o: src/runtime.cpp.o

.PHONY : src/runtime.o

# target to build an object file
src/runtime.cpp.o:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/runtime.cpp.o
.PHONY : src/runtime.cpp.o

src/runtime.i: src/runtime.cpp.i

.PHONY : src/runtime.i

# target to preprocess a source file
src/runtime.cpp.i:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/runtime.cpp.i
.PHONY : src/runtime.cpp.i

src/runtime.s: src/runtime.cpp.s

.PHONY : src/runtime.s

# target to generate assembly for a file
src/runtime.cpp.s:
	$(MAKE) -f CMakeFiles/mila+.dir/build.make CMakeFiles/mila+.dir/src/runtime.cpp.s
.PHONY : src/runtime.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... mila+"
	@echo "... edit_cache"
	@echo "... src/compiler.o"
	@echo "... src/compiler.i"
	@echo "... src/compiler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mila/ast.o"
	@echo "... src/mila/ast.i"
	@echo "... src/mila/ast.s"
	@echo "... src/mila/parser.o"
	@echo "... src/mila/parser.i"
	@echo "... src/mila/parser.s"
	@echo "... src/mila/scanner.o"
	@echo "... src/mila/scanner.i"
	@echo "... src/mila/scanner.s"
	@echo "... src/runtime.o"
	@echo "... src/runtime.i"
	@echo "... src/runtime.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

